### ISSUE TITLE
Multilined note

### ISSUE THREAD

**Issue by tomrule007** [wayneashleyberry/wunderlist-cli#73]
is it possible to add a multilined note?

$ wunderline add "Lines" --note "Line 1\nLine 2\nLine 3"

I've tried \n but didnt have any luck and I was wondering if there is a different command I should try. 

Thanks

**Comment by Thor77** [comment]
Currently not possible due to some problems with [`JSON.stringify`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) (escapes `\n` (correctly) to `\\n`), I opened an issue [wunderlist/api#85](https://github.com/wunderlist/api/issues/85) to make wunderlist-devs aware of that.

**Comment by alexandrebarbaruiva** [comment]
It's possible to add multilined notes by not closing the quote at the end of the line:

```
$ wunderline add "Lines" --note "Line1
> line2
> line3"
```

However I don't think that's a proper solution.

**Comment by Thor77** [comment]
The issue mentioned above applies here as well, though.
